apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-server
  namespace: minecraft
spec:
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
        - name: minecraft-server
          image: ghcr.io/nadmax/minekube:v1
          env:
            - name: EULA
              value: "TRUE"
            - name: VERSION
              value: "1.20.1"
            - name: MODE
              value: "survival"
            - name: TYPE
              value: "FORGE"
            - name: FORGEVERSION
              value: 47.4.10
            - name: INIT_MEMORY
              value: 4G
            - name: MAX_MEMORY
              value: 6G
            - name: GENERIC_PACK
              value: "/modpacks/mods.zip"
            - name: ALLOW_FLIGHT
              value: "TRUE"
            - name: USE_AIKAR_FLAGS
              value: "TRUE"
            - name: RCON_PASSWORD
              value: "rcon-password"
          ports:
            - name: minecraft
              containerPort: 25565
          resources:
            requests:
              cpu: 2
              memory: "6Gi"
            limits:
              cpu: 4
              memory: "6Gi"
          readinessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 60
          livenessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 120
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
            - name: modpacks
              mountPath: /modpacks
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-data
        - name: modpacks
          persistentVolumeClaim:
            claimName: modpacks
